### ISSUE TITLE
Wrong recipe installation instruction in custom chef README

### ISSUE THREAD

**Issue by radamanthus** [engineyard/ey-cookbooks-stable-v5#143]
A number of custom chef recipes have this in their installation instructions:

```
ey-core recipes upload --environment <nameofenvironment> --path <pathtocookbooksfolder> --apply
```

`ey-core` does not support the path parameter. It throws the error:

```
The application encountered the following error:
  invalid option: --path=cookbooks
```

Please remove the `--path` option on the instructions.

This following recipes need to be fixed:

- [cron](https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/examples/cron/cookbooks/custom-cron/README.md)
- [Elasticsearch](https://github.com/engineyard/ey-cookbooks-stable-v5/tree/next-release/examples/elasticsearch/cookbooks/custom-elasticsearch#installation)
- [logrotate](https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/examples/logrotate/cookbooks/custom-logrotate/README.md#installation)
- [memcached](https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/examples/memcached/cookbooks/custom-memcached/README.md#installation)
- [packages](https://github.com/engineyard/ey-cookbooks-stable-v5/tree/next-release/examples/packages/cookbooks/custom-packages#installation)
- [papertrail](https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/examples/papertrail/cookbooks/custom-papertrail/README.md#installation)
- [redis](https://github.com/engineyard/ey-cookbooks-stable-v5/tree/next-release/examples/redis/cookbooks/custom-redis#installation)
- [resque](https://github.com/engineyard/ey-cookbooks-stable-v5/tree/next-release/examples/resque/cookbooks/custom-resque#installation)
- [resque-scheduler](https://github.com/engineyard/ey-cookbooks-stable-v5/tree/next-release/examples/resque_scheduler/cookbooks/custom-resque_scheduler#installation)
- [thinking sphinx](https://github.com/engineyard/ey-cookbooks-stable-v5/tree/next-release/examples/thinking_sphinx_3/cookbooks/custom-thinking_sphinx_3#installation)

**Comment by dvalfre** [comment]
@radamanthus, @luxflux, `ey-core` supports `-f` to specify a path to  folder where the recipes live:

```
ENG001301:EngineYard dvalfre$ ey-core version
3.2.6
ENG001301:EngineYard dvalfre$
ENG001301:EngineYard dvalfre$ ey-core recipes upload --help
NAME
  upload - Upload custom recipes to an environment

SYNOPSIS
  ey-core recipes upload [upload options]

OPTIONS
  -c ACCOUNT, --account=ACCOUNT - Name of the account in which the environment
  can be found.
  -a, --apply - Apply the recipes immediately after they are uploaded
  -e ENVIRONMENT, --environment=ENVIRONMENT - Environment that will receive the
  recipes.
  -f PATH, --file=PATH - Path to recipes
  --no-wait - (used in conjunction with --apply) Don't wait for apply to finish,
  exit after started
  --verbose - (used in conjunction with --apply) verbose chef run (include chef
  setup and stack traces)
  --watch=INSTANCE - Specify an instance amazon_id or server role to watch chef
  logs (defaults to app_master)
  -h, --help - Shows this message
ENG001301:EngineYard dvalfre$
```

**Comment by radamanthus** [comment]
@dvalfre Thanks for pointing that out. I updated PR #https://github.com/engineyard/ey-cookbooks-stable-v5/pull/171. Mind giving it a review?

**Comment by radamanthus** [comment]
Fixed in https://github.com/engineyard/ey-cookbooks-stable-v5/releases/tag/3.0.24
