### ISSUE TITLE
PHP_ENV not set for cronjobs

### ISSUE THREAD

**Issue by themrwilliams** [engineyard/ey-cookbooks-stable-v5#189]
The app environment is correctly exposed to cron jobs for Ruby/Rack, but not for PHP.  From `crontab -l`:

```
RAILS_ENV="production"
RACK_ENV="production"
```

Just like with web and console scripts, I would expect to see `PHP_ENV` in there as well.

**Comment by rbankston** [comment]
Thanks for the pull request. It has been merged now.
