### ISSUE TITLE
First run of Sidekiq creates logfiles owned by root

### ISSUE THREAD

**Issue by dvalfre** [engineyard/ey-cookbooks-stable-v5#208]
[The fix](https://github.com/engineyard/ey-cookbooks-stable-v5/pull/157) for [how Monit on v5 starts Sidekiq processes](https://github.com/engineyard/ey-cookbooks-stable-v5/issues/154) introduced this issue:  the first time the command is run, the logfiles are created as with _root_ as the owner, and then Sidekiq running as _deploy_ can't open them.
The workaround for the time being is to manually run `sudo chown deploy: /var/log/engineyard/app/<app_name>/sidekiq*.log*`

**Comment by radamanthus** [comment]
We can redirect STDOUT to a temp file not used by Sidekiq.

Change: https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/sidekiq/files/default/sidekiq#L69

From:

```
sudo -u "${app_user}" -E -H "${sidekiq}" -d -C "${conf_file}" -e "${rails_env}" -r "${app_root}" -P "${pid_file}" -L "${log_file}" -i ${worker_id} >> ${log_file} 2>&1 &
```

to:

```
sudo -u "${app_user}" -E -H "${sidekiq}" -d -C "${conf_file}" -e "${rails_env}" -r "${app_root}" -P "${pid_file}" -L "${log_file}" -i ${worker_id} >> /tmp/sidekiq.stdout 2>&1 &
```

**Comment by radamanthus** [comment]
Better: 

- Use worker_id so that there's one stdout file for each worker
- use `/mnt/tmp`, that partition has more available space

```
sudo -u "${app_user}" -E -H "${sidekiq}" -d -C "${conf_file}" -e "${rails_env}" -r "${app_root}" -P "${pid_file}" -L "${log_file}" -i ${worker_id} >> /mnt/tmp/sidekiq_${worker_id}.stdout 2>&1 &
```

**Comment by radamanthus** [comment]
Fixed in https://github.com/engineyard/ey-cookbooks-stable-v5/releases/tag/3.0.30
