### ISSUE TITLE
Consider using passenger-config detach instead of kill -9

### ISSUE THREAD

**Issue by radamanthus** [engineyard/ey-cookbooks-stable-v5#213]
If a Passenger5 worker is bloated after _grace_time_ seconds, we terminate it with `kill -9` here:
https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/passenger5/files/default/passenger_monitor#L78

We should consider using `passenger-config detach` instead. This solution was recommended here: https://github.com/brianmario/mysql2/issues/772#issuecomment-261593963

**Comment by dvalfre** [comment]
Need a way to generate bloated Passenger workers.  @radamanthus got an example at hand?

**Comment by radamanthus** [comment]
@dvalfre When testing Passenger bloat I set a very very low limit (e.g. 1MB) to trigger termination

**Comment by radamanthus** [comment]
The `kill -USR1` line is what should be replaced by `passenger-config detach`. https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/passenger5/files/default/passenger_monitor#L73

http://old.blog.phusion.nl/category/passenger/phusion-passenger-5/

```
Using the SIGUSR1 signal to restart a Ruby app without dropping connections, is no longer supported. Instead, use `passenger-config detach-process`.
```

**Comment by radamanthus** [comment]
Fixed: https://github.com/engineyard/ey-cookbooks-stable-v5/releases/tag/3.0.31

**Comment by mikong** [comment]
Seems we still use `kill -USR1` and not `passenger-config detach`. Reopening.

**Comment by jegasega** [comment]
Fixed in the https://github.com/engineyard/ey-cookbooks-stable-v5/pull/304
