### ISSUE TITLE
DelayedJob script improvement

### ISSUE THREAD

**Issue by radamanthus** [engineyard/ey-cookbooks-stable-v5#221]
We only wait for the bash command that launches DelayedJob: https://github.com/engineyard/ey-cookbooks-stable-v5/blame/next-release/cookbooks/delayed_job4/templates/default/dj.erb#L161

It's possible that the bash command stops and the actual dj process doesn't and its parent becomes PID 1

We should terminate both the bash command and the dj process

**Comment by radamanthus** [comment]
Restating the original issue.

We terminate the bash command and the dj process here, with a `kill -15`: https://github.com/engineyard/ey-cookbooks-stable-v5/blame/next-release/cookbooks/delayed_job4/templates/default/dj.erb#L157

If that kill ends up terminating the bash process but not the dj worker, then execution won't enter this block: https://github.com/engineyard/ey-cookbooks-stable-v5/blame/next-release/cookbooks/delayed_job4/templates/default/dj.erb#L161-L173. The dj worker will not be terminated and will linger on.

Scenario 1: Line 157 terminated both the bash process and the dj worker. Lines 161-173 will be skipped. All good here.

Scenario 2: Line 157 terminated the bash process but not the dj worker. Lines 161-173 will be skipped. The dj worker will linger on. This is the bug we want to address.

Scenario 3: Line 157 terminated the dj worker but not the bash process. Lines 161-173 will be run. bash process will be terminated. $WORKER_PID will be terminated again - hopefully that PID hasn't yet been assigned to another process (bug)

Scenario 4: Line 157 did not terminate the bash process nor the dj worker. Lines 161-173 will be run. Both the bash process and the dj worker will be terminated with kill -9. All good here.

**Comment by crigor** [comment]
Correct. You'll want another check similar to 161-173 for the WORKER_PID to address Scenario 2.

**Comment by radamanthus** [comment]
Internal EngineYard ticket: CC-1192

**Comment by radamanthus** [comment]
This will be addressed by PR #224. Please close this once that PR has been merged and released.

**Comment by radamanthus** [comment]
Fixed on https://github.com/engineyard/ey-cookbooks-stable-v5/releases/tag/3.0.31
