### ISSUE TITLE
Improve how sidekiq recipe changes database.yml

### ISSUE THREAD

**Issue by radamanthus** [engineyard/ey-cookbooks-stable-v5#227]
The sidekiq recipe updates database.yml to set the number of DB connections according to the node['sidekiq']['concurrency'] setting:
https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/sidekiq/recipes/setup.rb#L44

This is OK as long as there is only one sidekiq process running. 

The DB connection pool setting should be set to `node['sidekiq']['workers'] * node['sidekiq']['concurrency]'`

We provide instructions on how to customize the number of workers here:
https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/custom-cookbooks/sidekiq/cookbooks/custom-sidekiq/README.md#choose-the-number-of-sidekiq-processes

**Comment by tpoland** [comment]
I don't think this is correct, see https://github.com/engineyard/ey-cloud-recipes/pull/332 before proceeding with this change.

**Comment by JBRC-ph** [comment]
Great explanation in that thread @tpoland. Thanks for the catch. 

I'll remove this change from next-release.

**Comment by radamanthus** [comment]
Great explanation in that thread @tpoland. Thanks for the catch.

I'll remove this change from next-release.

**Comment by radamanthus** [comment]
It looks like there's no pull request yet for this, so there's nothing to remove. 

Closing this issue.
