### ISSUE TITLE
Make the puma restart sleep timeout configurable

### ISSUE THREAD

**Issue by radamanthus** [engineyard/ey-cookbooks-stable-v5#282]
On this line: https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/puma/templates/default/app_control.erb#L127

Get the sleep timeout from the puma recipe's attributes/puma.rb file

This way it can be easier to customize how puma behaves simply by creating an overlay recipe that changes attributes/puma.rb

**Comment by vraravam** [comment]
@radamanthus - let me take a crack at this.

**Comment by radamanthus** [comment]
Thanks for this @vraravam! This looks good but is missing something. We also need to include sleep_timeout in the variables passed here: https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/puma/recipes/default.rb#L60-L75

Something like 

```
:sleep_timeout => node['puma']['sleep_timeout']
```

between lines 71 and 72

**Comment by radamanthus** [comment]
Sorry, my previous comment is wrong. The block that needs to be modified is https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/puma/recipes/default.rb#L92-L98

**Comment by DalianisDim** [comment]
Fixed on #339

**Comment by dvalfre** [comment]
@DalianisDim are we ok to close this issue?

**Comment by DalianisDim** [comment]
Yes, closing
