### ISSUE TITLE
monit.d directory is not symlinked to /data/monit.d

### ISSUE THREAD

**Issue by radamanthus** [engineyard/ey-cookbooks-stable-v5#334]
Stack version: stable-v5-3.0.36
Environment: Solo
Recipes used: memcached, redis

The redis recipe writes its monitrc in `/data/monit.d/redis.monitrc`
The memcached recipe writes in `/etc/monit.d/memcached.monitrc`. 

By itself this shouldn't be a problem because `/etc/monit.d/` is a symlink to `/data/monit.d/`.

However under certain circumstances - possibly when the memcached recipe is used, `/etc/monit.d/` ends up as a directory and not a symlink to `/data/monit.d`.

This block in the memcached recipe is responsible: https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/memcached/recipes/install.rb#L43-L48

---

Possible workaround (not tested):

Following the approach described in https://github.com/engineyard/ey-cookbooks-stable-v5/wiki/Customizing-Your-Environment-Using-Overlay-Chef-Recipes, create an overlay recipe to override `memcached/recipes/install.rb`.

- create `cookbooks/memcached/recipes/install.rb`
- copy the code in https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/memcached/recipes/install.rb but remove the block identified in the bug
- upload the recipe and run chef

**Comment by gengor** [comment]
This is YT-CC-1238.
