### ISSUE TITLE
custom-delayd_job4 example error: Cookbook delayed_job4 not found

### ISSUE THREAD

**Issue by PiotrMisiurek** [engineyard/ey-cookbooks-stable-v5#57]
I have just copied recipes `ey-custom` and `custom-delayed_job` from [delayed_job4 example](https://github.com/engineyard/ey-cookbooks-stable-v5/tree/next-release/examples/delayed_job4/cookbooks)

When I try to upload and apply recipes I received an error: `Cookbook delayed_job4 not found. If you're loading delayed_job4 from another cookbook, make sure you configure the dependency in your metadata`

`delayed_job4`dependency is in [custom-delayed_job4 metadata file](https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/examples/delayed_job4/cookbooks/custom-delayed_job4/metadata.rb)

Is there sth i did wrong? Or the example is not working?

**Comment by crigor** [comment]
@PiotrMisiurek Are you using the v5 stack? Can you open a Support ticket so we can look into your instances?

**Comment by PiotrMisiurek** [comment]
I upgraded stack to `stable-v5-3.0.15` from`stable-v5-3.0.14` and it solved issue
